package POJO;
// Generated May 22, 2015 11:13:05 AM by Hibernate Tools 4.3.1



/**
 * Budget generated by hbm2java
 */
public class Budget  implements java.io.Serializable {


     private Integer id;
     private Integer idUser;
     private int idKategori;
     private Integer siklus;
     private Double batas;
     private int rollover;

    public Budget() {
    }

	
    public Budget(int idKategori, int rollover) {
        this.idKategori = idKategori;
        this.rollover = rollover;
    }
    public Budget(Integer idUser, int idKategori, Integer siklus, Double batas, int rollover) {
       this.idUser = idUser;
       this.idKategori = idKategori;
       this.siklus = siklus;
       this.batas = batas;
       this.rollover = rollover;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public int getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(int idKategori) {
        this.idKategori = idKategori;
    }
    public Integer getSiklus() {
        return this.siklus;
    }
    
    public void setSiklus(Integer siklus) {
        this.siklus = siklus;
    }
    public Double getBatas() {
        return this.batas;
    }
    
    public void setBatas(Double batas) {
        this.batas = batas;
    }
    public int getRollover() {
        return this.rollover;
    }
    
    public void setRollover(int rollover) {
        this.rollover = rollover;
    }




}


