package POJO;
// Generated Mar 6, 2015 3:45:07 PM by Hibernate Tools 4.3.1

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

    private Integer id;
    private Integer jenis;
    private String nama;
    private Integer idUser;

    public Category() {
    }

    public Category(Integer jenis, String nama, Integer idUser) {
        this.jenis = jenis;
        this.nama = nama;
        this.idUser = idUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getJenis() {
        return this.jenis;
    }

    public void setJenis(Integer jenis) {
        this.jenis = jenis;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

}
