package POJO;
// Generated May 22, 2015 11:13:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reminder generated by hbm2java
 */
public class Reminder  implements java.io.Serializable {


     private Integer id;
     private Integer idUser;
     private Date tglBuat;
     private Date tglKirim;
     private String deskripsi;

    public Reminder() {
    }

	
    public Reminder(Date tglBuat, Date tglKirim) {
        this.tglBuat = tglBuat;
        this.tglKirim = tglKirim;
    }
    public Reminder(Integer idUser, Date tglBuat, Date tglKirim, String deskripsi) {
       this.idUser = idUser;
       this.tglBuat = tglBuat;
       this.tglKirim = tglKirim;
       this.deskripsi = deskripsi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Date getTglBuat() {
        return this.tglBuat;
    }
    
    public void setTglBuat(Date tglBuat) {
        this.tglBuat = tglBuat;
    }
    public Date getTglKirim() {
        return this.tglKirim;
    }
    
    public void setTglKirim(Date tglKirim) {
        this.tglKirim = tglKirim;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


