package POJO;
// Generated May 22, 2015 11:13:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer id;
     private Integer idUser;
     private Date tglTransaksi;
     private String deskripsi;
     private Double amount;
     private Integer jenis;
     private Integer idKategori;
     private String mataUang;

    public Transaction() {
    }

	
    public Transaction(Date tglTransaksi) {
        this.tglTransaksi = tglTransaksi;
    }
    public Transaction(Integer user, Date tglTransaksi, String deskripsi, Double amount, Integer jenis, Integer idKategori, String mataUang) {
       this.idUser = user;
       this.tglTransaksi = tglTransaksi;
       this.deskripsi = deskripsi;
       this.amount = amount;
       this.jenis = jenis;
       this.idKategori = idKategori;
       this.mataUang = mataUang;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer user) {
        this.idUser = user;
    }
    public Date getTglTransaksi() {
        return this.tglTransaksi;
    }
    
    public void setTglTransaksi(Date tglTransaksi) {
        this.tglTransaksi = tglTransaksi;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getJenis() {
        return this.jenis;
    }
    
    public void setJenis(Integer jenis) {
        this.jenis = jenis;
    }
    public Integer getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(Integer idKategori) {
        this.idKategori = idKategori;
    }
    public String getMataUang() {
        return this.mataUang;
    }
    
    public void setMataUang(String mataUang) {
        this.mataUang = mataUang;
    }




}


