package POJO;
// Generated Mar 6, 2015 3:45:07 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

    private Integer id;
    private int idUser;
    private Date tglTransaksi;
    private String deskripsi;
    private Integer amount;
    private Integer jenis;
    private Integer idKategori;
    private String mataUang;

    public Transaction() {
    }

    public Transaction(int idUser, Date tglTransaksi, String deskripsi, Integer amount, Integer jenis, Integer idKategori, String mataUang) {
        this.idUser = idUser;
        this.tglTransaksi = tglTransaksi;
        this.deskripsi = deskripsi;
        this.amount = amount;
        this.jenis = jenis;
        this.idKategori = idKategori;
        this.mataUang = mataUang;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public Date getTglTransaksi() {
        return this.tglTransaksi;
    }

    public void setTglTransaksi(Date tglTransaksi) {
        this.tglTransaksi = tglTransaksi;
    }

    public String getDeskripsi() {
        return this.deskripsi;
    }

    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }

    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Integer getJenis() {
        return this.jenis;
    }

    public void setJenis(Integer jenis) {
        this.jenis = jenis;
    }

    public Integer getIdKategori() {
        return this.idKategori;
    }

    public void setIdKategori(Integer idKategori) {
        this.idKategori = idKategori;
    }

    public String getMataUang() {
        return this.mataUang;
    }

    public void setMataUang(String mataUang) {
        this.mataUang = mataUang;
    }

}
