package POJO;
// Generated May 22, 2015 11:13:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String email;
     private String password;
     private String token;
     private Set transactions = new HashSet(0);

    public User() {
    }

	
    public User(String nama, String email, String password) {
        this.nama = nama;
        this.email = email;
        this.password = password;
    }
    public User(String nama, String email, String password, String token, Set transactions) {
       this.nama = nama;
       this.email = email;
       this.password = password;
       this.token = token;
       this.transactions = transactions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


